# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu

pipelines:
  default:
    - step:
        name: 'Build'
        script:
          - apt update -y
          - apt install wget -y
#          - apt install puppet -y
          - ls
          - export DEBIAN_FRONTEND=noninteractive
          - tempdeb=$(mktemp /tmp/debpackage.XXXXXXXXXXXXXXXXXX) || exit 1
          - i=0;
          - wget -O "$tempdeb" https://apt.puppetlabs.com/puppet6-release-bionic.deb
          - ret="$?"
          - while [ "$i" -lt "5" ] && [ "$ret" -ne "0" ]; do wget -O "$tempdeb" https://apt.puppetlabs.com/puppet6-release-bionic.deb ; ret="$?" ; let "i++" ; done
          - if [ "$ret" -ne "0" ]; then exit 1003; fi
          - dpkg -i "$tempdeb"
          - apt update -y
#          - apt-get -y install puppetserver git pwgen
          - apt install puppetserver
          - apt install puppet-lint
#          - /opt/puppetlabs/bin/puppet --verion

#    - step:
#        name: 'Lint'
#        script:
#          - puppet-lint site-modules/*/manifests/*.pp
#          - puppet-lint manifests/site.pp
#    - step:
#        name: 'Validate'
#        script:
#          - /opt/puppetlabs/bin/puppet parser validate site-modules/*/manifests/*.pp
#          - /opt/puppetlabs/bin/puppet parser validate manifests/site.pp
#    - step:
#        name: 'Test'
#        script:
#          - echo "Your security scan goes here..."
#
#    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
#    - step:
#        name: 'Deployment to Staging'
#        deployment: staging
#        script:
#          - echo "Your deployment to staging script goes here..."
#    - step:
#        name: 'Deployment to Production'
#        deployment: production
#        trigger: 'manual'
#        script:
#          - echo "Your deployment to production script goes here..."
#
